# Generated by Django 5.2 on 2025-04-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_recentwork_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentwork',
            old_name='tiltle',
            new_name='title',
        ),
    ]
